#!/usr/bin/env python3
"""Check/export the cross-language research outcome v3 contract.

The schema is deliberately kept dependency-free so a fresh deployment and CI
can verify the contract before installing the full application stack.  The
Python reducer and the two TypeScript projections are checked for the same
version and vocabulary; business code must not silently ship a second set of
status meanings.

Usage::

    python scripts/export_outcome_contract.py --check
    python scripts/export_outcome_contract.py --write
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "contracts" / "research_outcome_v3.schema.json"
GENERATED_TARGETS = (
    ROOT / "server" / "generated" / "research-outcome-v3.ts",
    ROOT / "web" / "src" / "generated" / "research-outcome-v3.ts",
)
VERSION = "research-outcome/3.0.0"
LEGACY_VERSION = "research-outcome/2.0.0"
EXPECTED_ENUMS = {
    "JobStatus": ["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", "STALE"],
    "LifecycleState": ["QUEUED", "RUNNING", "TERMINAL"],
    "QualityState": ["VALIDATED", "DEGRADED", "BLOCKED", "FAILED", "CANCELLED"],
    "SufficiencyState": ["SUFFICIENT", "PARTIAL", "INSUFFICIENT", "NOT_APPLICABLE"],
    "OpportunityState": ["PRESENT", "ABSENT", "UNKNOWN", "NOT_APPLICABLE"],
    "ActionabilityState": ["ACTIONABLE", "NO_ACTION", "UNKNOWN", "NOT_APPLICABLE"],
    "PublicationState": ["READY", "NOT_APPLICABLE", "BLOCKED", "PUBLISHED"],
}
REQUIRED_COMMON = {
    "schema_version",
    "job_status",
    "lifecycle_state",
    "quality_state",
    "data_sufficiency_state",
    "research_opportunity_state",
    "focus_opportunity_state",
    "actionability_state",
    "publication_state",
    "reason_codes",
    "counts",
    "data_coverage",
    "legacy_status",
}


def _load_schema() -> dict[str, Any]:
    try:
        value = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise RuntimeError(f"missing contract schema: {SCHEMA_PATH}") from exc
    if not isinstance(value, dict):
        raise RuntimeError("contract schema root must be an object")
    return value


def _required_from_common(schema: dict[str, Any]) -> set[str]:
    common = schema.get("$defs", {}).get("Common", {})
    required = common.get("required", []) if isinstance(common, dict) else []
    return set(required) if isinstance(required, list) else set()


def _source_check(path: Path, required: list[str]) -> list[str]:
    try:
        source = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return [f"missing source projection: {path.relative_to(ROOT)}"]
    errors: list[str] = []
    if VERSION not in source:
        errors.append(f"{path.relative_to(ROOT)} does not declare {VERSION}")
    for token in required:
        if token not in source:
            errors.append(f"{path.relative_to(ROOT)} is missing contract token {token}")
    return errors


def _typescript_union(schema: dict[str, Any], definition: str) -> str:
    values = schema["$defs"][definition]["enum"]
    return " | ".join(json.dumps(value) for value in values)


def render_typescript(schema: dict[str, Any]) -> str:
    """Generate the dependency-free TypeScript exchange contract."""

    return f'''// Generated by scripts/export_outcome_contract.py. DO NOT EDIT.
export const RESEARCH_OUTCOME_SCHEMA_VERSION = {json.dumps(VERSION)} as const;

export type OutcomeJobStatus = {_typescript_union(schema, "JobStatus")};
export type OutcomeLifecycleState = {_typescript_union(schema, "LifecycleState")};
export type OutcomeQualityState = {_typescript_union(schema, "QualityState")};
export type OutcomeDataSufficiencyState = {_typescript_union(schema, "SufficiencyState")};
export type OutcomeOpportunityState = {_typescript_union(schema, "OpportunityState")};
export type OutcomeActionabilityState = {_typescript_union(schema, "ActionabilityState")};
export type OutcomePublicationState = {_typescript_union(schema, "PublicationState")};

export interface OutcomeCounts {{
  readonly [key: string]: number;
}}

export interface OutcomeDataCoverage {{
  readonly [key: string]: number | string | null;
}}

export interface StageOutcomeContract {{
  readonly schema_version: typeof RESEARCH_OUTCOME_SCHEMA_VERSION;
  readonly stage: string;
  readonly job_status: OutcomeJobStatus;
  readonly lifecycle_state: OutcomeLifecycleState;
  readonly quality_state: OutcomeQualityState;
  readonly data_sufficiency_state: OutcomeDataSufficiencyState;
  readonly research_opportunity_state: OutcomeOpportunityState;
  readonly focus_opportunity_state: OutcomeOpportunityState;
  readonly actionability_state: OutcomeActionabilityState;
  readonly opportunity_state: OutcomeOpportunityState;
  readonly publication_state: OutcomePublicationState;
  readonly reason_codes: readonly string[];
  readonly counts: OutcomeCounts;
  readonly data_coverage: OutcomeDataCoverage;
  readonly legacy_status: string;
}}

export interface LaneOutcomeContract {{
  readonly schema_version: typeof RESEARCH_OUTCOME_SCHEMA_VERSION;
  readonly lane_id: string;
  readonly model: string | null;
  readonly job_status: OutcomeJobStatus;
  readonly lifecycle_state: OutcomeLifecycleState;
  readonly quality_state: OutcomeQualityState;
  readonly data_sufficiency_state: OutcomeDataSufficiencyState;
  readonly research_opportunity_state: OutcomeOpportunityState;
  readonly focus_opportunity_state: OutcomeOpportunityState;
  readonly actionability_state: OutcomeActionabilityState;
  readonly opportunity_state: OutcomeOpportunityState;
  readonly publication_state: OutcomePublicationState;
  readonly reason_codes: readonly string[];
  readonly counts: OutcomeCounts;
  readonly data_coverage: OutcomeDataCoverage;
  readonly legacy_status: string;
  readonly stages: readonly StageOutcomeContract[];
}}

export interface RunOutcomeContract {{
  readonly schema_version: typeof RESEARCH_OUTCOME_SCHEMA_VERSION;
  readonly run_id: string | null;
  readonly job_status: OutcomeJobStatus;
  readonly lifecycle_state: OutcomeLifecycleState;
  readonly quality_state: OutcomeQualityState;
  readonly data_sufficiency_state: OutcomeDataSufficiencyState;
  readonly research_opportunity_state: OutcomeOpportunityState;
  readonly focus_opportunity_state: OutcomeOpportunityState;
  readonly actionability_state: OutcomeActionabilityState;
  readonly opportunity_state?: OutcomeOpportunityState;
  readonly publication_state: OutcomePublicationState;
  readonly reason_codes: readonly string[];
  readonly counts: OutcomeCounts;
  readonly data_coverage: OutcomeDataCoverage;
  readonly legacy_status: string;
  readonly primary_lane_ids: readonly string[];
  readonly comparison_status: string;
  readonly lanes: readonly LaneOutcomeContract[];
}}
'''


def check() -> tuple[str, ...]:
    errors: list[str] = []
    try:
        schema = _load_schema()
    except RuntimeError as exc:
        return (str(exc),)
    if schema.get("$schema") != "https://json-schema.org/draft/2020-12/schema":
        errors.append("schema must use JSON Schema draft 2020-12")
    defs = schema.get("$defs")
    if not isinstance(defs, dict):
        return ("schema is missing $defs",)
    for name, expected in EXPECTED_ENUMS.items():
        item = defs.get(name)
        actual = item.get("enum") if isinstance(item, dict) else None
        if actual != expected:
            errors.append(f"$defs.{name}.enum does not match canonical vocabulary")
    version = defs.get("SchemaVersion", {})
    if not isinstance(version, dict) or version.get("const") != VERSION:
        errors.append("$defs.SchemaVersion must be research-outcome/3.0.0")
    legacy = defs.get("LegacySchemaVersion", {})
    if not isinstance(legacy, dict) or legacy.get("const") != LEGACY_VERSION:
        errors.append("$defs.LegacySchemaVersion must be research-outcome/2.0.0")
    if _required_from_common(schema) != REQUIRED_COMMON:
        errors.append("$defs.Common.required is not the canonical v3 field set")
    errors.extend(_source_check(ROOT / "src" / "liangjian_funnel" / "pipeline" / "outcomes.py", [VERSION, "data_sufficiency_state", "research_opportunity_state", "focus_opportunity_state", "actionability_state"]))
    errors.extend(_source_check(ROOT / "server" / "types.ts", [VERSION, "generated/research-outcome-v3"]))
    errors.extend(_source_check(ROOT / "web" / "src" / "types.ts", [VERSION, "data_sufficiency_state", "research_opportunity_state", "focus_opportunity_state", "actionability_state"]))
    generated = render_typescript(schema)
    for target in GENERATED_TARGETS:
        try:
            actual = target.read_text(encoding="utf-8")
        except FileNotFoundError:
            errors.append(f"missing generated TypeScript contract: {target.relative_to(ROOT)}")
            continue
        if actual != generated:
            errors.append(f"generated TypeScript contract has drift: {target.relative_to(ROOT)}")
    return tuple(errors)


def write() -> None:
    schema = _load_schema()
    SCHEMA_PATH.write_text(json.dumps(schema, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    generated = render_typescript(schema)
    for target in GENERATED_TARGETS:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate schema and source projections")
    parser.add_argument("--write", action="store_true", help="canonicalize the checked schema JSON")
    args = parser.parse_args()
    if args.write:
        write()
    errors = check()
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    digest = hashlib.sha256(SCHEMA_PATH.read_bytes()).hexdigest()[:16]
    print(f"outcome contract OK: {VERSION} schema_sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
